// ActorSIMOToken4qsys_ActorSIMOToken4_0.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module ActorSIMOToken4qsys_ActorSIMOToken4_0 (
		input  wire        clock,    // clock.clk
		input  wire        resetn,   // reset.reset_n
		input  wire [31:0] s0_data,  //    s0.data
		output wire        s0_ready, //      .ready
		input  wire        s0_valid, //      .valid
		output wire [31:0] s1_data,  //    s1.data
		input  wire        s1_ready, //      .ready
		output wire        s1_valid  //      .valid
	);

	ActorSIMOToken4_internal actorsimotoken4_internal_inst (
		.clock    (clock),    // clock.clk
		.resetn   (resetn),   // reset.reset_n
		.s0_data  (s0_data),  //    s0.data
		.s0_ready (s0_ready), //      .ready
		.s0_valid (s0_valid), //      .valid
		.s1_data  (s1_data),  //    s1.data
		.s1_ready (s1_ready), //      .ready
		.s1_valid (s1_valid)  //      .valid
	);

endmodule
