// initialalwasyqsys_Pinitialsalways_0.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module initialalwasyqsys_Pinitialsalways_0 (
		input  wire        clock,    // clock.clk
		input  wire        resetn,   // reset.reset_n
		input  wire [31:0] s0_data,  //    s0.data
		output wire        s0_ready, //      .ready
		input  wire        s0_valid, //      .valid
		output wire [31:0] s3_data,  //    s3.data
		input  wire        s3_ready, //      .ready
		output wire        s3_valid  //      .valid
	);

	Pinitialsalways_internal pinitialsalways_internal_inst (
		.clock    (clock),    // clock.clk
		.resetn   (resetn),   // reset.reset_n
		.s0_data  (s0_data),  //    s0.data
		.s0_ready (s0_ready), //      .ready
		.s0_valid (s0_valid), //      .valid
		.s3_data  (s3_data),  //    s3.data
		.s3_ready (s3_ready), //      .ready
		.s3_valid (s3_valid)  //      .valid
	);

endmodule
