// ActorMultioutputTokenqsys_ActorMultioutputToken_0.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module ActorMultioutputTokenqsys_ActorMultioutputToken_0 (
		input  wire        clock,    // clock.clk
		input  wire        resetn,   // reset.reset_n
		output wire [31:0] s1_data,  //    s1.data
		input  wire        s1_ready, //      .ready
		output wire        s1_valid, //      .valid
		output wire [31:0] s2_data,  //    s2.data
		input  wire        s2_ready, //      .ready
		output wire        s2_valid  //      .valid
	);

	ActorMultioutputToken_internal actormultioutputtoken_internal_inst (
		.clock    (clock),    // clock.clk
		.resetn   (resetn),   // reset.reset_n
		.s1_data  (s1_data),  //    s1.data
		.s1_ready (s1_ready), //      .ready
		.s1_valid (s1_valid), //      .valid
		.s2_data  (s2_data),  //    s2.data
		.s2_ready (s2_ready), //      .ready
		.s2_valid (s2_valid)  //      .valid
	);

endmodule
