// FB_Streaminoutqsys_Streaminout_2.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module FB_Streaminoutqsys_Streaminout_2 (
		input  wire [31:0] a_data,  //      a.data
		output wire        a_ready, //       .ready
		input  wire        a_valid, //       .valid
		output wire [31:0] b_data,  //      b.data
		input  wire        b_ready, //       .ready
		output wire        b_valid, //       .valid
		input  wire        start,   //   call.valid
		output wire        busy,    //       .stall
		input  wire        clock,   //  clock.clk
		input  wire        resetn,  //  reset.reset_n
		output wire        done,    // return.valid
		input  wire        stall    //       .stall
	);

	FB_Streaminout_internal fb_streaminout_internal_inst (
		.clock   (clock),   //  clock.clk
		.resetn  (resetn),  //  reset.reset_n
		.a_data  (a_data),  //      a.data
		.a_ready (a_ready), //       .ready
		.a_valid (a_valid), //       .valid
		.b_data  (b_data),  //      b.data
		.b_ready (b_ready), //       .ready
		.b_valid (b_valid), //       .valid
		.start   (start),   //   call.valid
		.busy    (busy),    //       .stall
		.done    (done),    // return.valid
		.stall   (stall)    //       .stall
	);

endmodule
